// Enhanced Mock Data with Category-Specific Details for Portfolio Detail

export const mockAssetData = {
  tesla: {
    id: "tesla",
    name: "Tesla Inc.",
    symbol: "TSLA",
    icon: "🚗",
    type: "stock",
    category: "stocks" as const,
    currentValue: 1245000,
    performance: 12.5,
    allocation: 18.2,
    holdingPeriod: "2 years 3 months",
    riskLevel: "High",
    units: 500,
    avgBuyPrice: 180.5,
    currentPrice: 249.0,
    unrealizedGain: 342500,
    totalInvested: 902500,
    dividendReceived: 12500,
    projectedValue: 2000000,
    projectedTimeframe: "5 years",
    volatility: 0.68,
    diversificationImpact: "High concentration risk",
    goalAllocation: {
      retirement: 40,
      travel: 20,
      emergency: 0,
      house: 40,
    },
    transactions: [
      {
        date: "2024-08-15",
        type: "buy",
        amount: 100,
        price: 245.0,
        total: 24500,
        icon: "💸",
      },
      {
        date: "2024-06-20",
        type: "dividend",
        amount: 0,
        price: 0,
        total: 2500,
        icon: "💰",
      },
      {
        date: "2024-03-10",
        type: "buy",
        amount: 200,
        price: 190.0,
        total: 38000,
        icon: "💸",
      },
      {
        date: "2023-12-05",
        type: "dividend",
        amount: 0,
        price: 0,
        total: 5000,
        icon: "💰",
      },
      {
        date: "2023-08-22",
        type: "buy",
        amount: 200,
        price: 175.0,
        total: 35000,
        icon: "💸",
      },
    ],
    performanceData: [
      { date: "2023-08", value: 35000 },
      { date: "2023-12", value: 40000 },
      { date: "2024-03", value: 73000 },
      { date: "2024-06", value: 75500 },
      { date: "2024-08", value: 100000 },
      { date: "2024-09", value: 124500 },
    ],
    // Category-specific data for stocks
    categoryData: {
      totalValue: 1245000,
      todayChange: 15420,
      allocation: 18.2,
      holdings: [
        {
          ticker: "TSLA",
          name: "Tesla Inc.",
          units: 500,
          value: 124500,
          change: 12.5,
        },
        {
          ticker: "AAPL",
          name: "Apple Inc.",
          units: 200,
          value: 34000,
          change: 8.2,
        },
        {
          ticker: "GOOGL",
          name: "Alphabet Inc.",
          units: 150,
          value: 45000,
          change: -2.1,
        },
        {
          ticker: "MSFT",
          name: "Microsoft Corp.",
          units: 100,
          value: 41000,
          change: 15.7,
        },
      ],
    },
  },
  crypto: {
    id: "crypto",
    name: "Cryptocurrency Portfolio",
    symbol: "CRYPTO",
    icon: "₿",
    type: "crypto",
    category: "crypto" as const,
    currentValue: 45000,
    performance: -12.3,
    allocation: 5,
    holdingPeriod: "1 year 8 months",
    riskLevel: "High",
    volatility: 0.85,
    diversificationImpact: "High volatility asset",
    performanceData: [
      { date: "2023-08", value: 52000 },
      { date: "2023-12", value: 48000 },
      { date: "2024-03", value: 55000 },
      { date: "2024-06", value: 42000 },
      { date: "2024-08", value: 47000 },
      { date: "2024-09", value: 45000 },
    ],
    categoryData: {
      totalValue: 45000,
      todayChange: -8.5,
      volatility: 0.85,
      holdings: [
        {
          symbol: "BTC",
          name: "Bitcoin",
          units: 0.75,
          value: 28000,
          change: -5.2,
        },
        {
          symbol: "ETH",
          name: "Ethereum",
          units: 8.5,
          value: 15000,
          change: -15.8,
        },
        {
          symbol: "ADA",
          name: "Cardano",
          units: 2500,
          value: 2000,
          change: 12.3,
        },
      ],
    },
  },
  cash: {
    id: "cash",
    name: "Cash & Savings",
    symbol: "CASH",
    icon: "💰",
    type: "cash",
    category: "cash" as const,
    currentValue: 125000,
    performance: 2.5,
    allocation: 25,
    holdingPeriod: "Ongoing",
    riskLevel: "Low",
    volatility: 0.02,
    diversificationImpact: "Stability anchor",
    performanceData: [
      { date: "2023-08", value: 120000 },
      { date: "2023-12", value: 121000 },
      { date: "2024-03", value: 122500 },
      { date: "2024-06", value: 123800 },
      { date: "2024-08", value: 124500 },
      { date: "2024-09", value: 125000 },
    ],
    categoryData: {
      totalCash: 125000,
      emergencyFundMonths: 8.5,
      interestRate: 4.2,
      accounts: [
        {
          id: "1",
          name: "High-Yield Savings",
          type: "Savings",
          balance: 75000,
          interestRate: 4.5,
          monthlyInterest: 281,
        },
        {
          id: "2",
          name: "Checking Account",
          type: "Checking",
          balance: 25000,
          interestRate: 0.1,
          monthlyInterest: 2,
        },
        {
          id: "3",
          name: "Money Market",
          type: "Money Market",
          balance: 25000,
          interestRate: 3.8,
          monthlyInterest: 79,
        },
      ],
    },
  },
};

// Portfolio Assets for Wealth Wheel
export const portfolioAssets = [
  {
    id: "stocks",
    name: "Stocks",
    value: 280000,
    allocation: 45,
    color: "#3B82F6",
    icon: "📈",
    performance: 15.2,
  },
  {
    id: "cash",
    name: "Cash",
    value: 125000,
    allocation: 25,
    color: "#10B981",
    icon: "💰",
    performance: 2.5,
  },
  {
    id: "funds",
    name: "Funds",
    value: 150000,
    allocation: 20,
    color: "#8B5CF6",
    icon: "🏦",
    performance: 8.7,
  },
  {
    id: "crypto",
    name: "Crypto",
    value: 45000,
    allocation: 5,
    color: "#F59E0B",
    icon: "₿",
    performance: -12.3,
  },
  {
    id: "real_estate",
    name: "Real Estate",
    value: 85000,
    allocation: 5,
    color: "#EF4444",
    icon: "🏠",
    performance: 6.8,
  },
];

// Achievement System
export const mockPortfolioAchievements = [
  {
    id: "first_100k",
    title: "First $100K",
    description: "Reached your first $100,000 milestone",
    icon: "🏆",
    earned: true,
    rarity: "rare" as const,
  },
  {
    id: "diversification_hero",
    title: "Diversification Hero",
    description: "Portfolio spread across 5+ asset types",
    icon: "🎯",
    earned: true,
    rarity: "epic" as const,
  },
  {
    id: "diamond_hands",
    title: "Diamond Hands",
    description: "Held investments through market volatility",
    icon: "💎",
    earned: true,
    rarity: "legendary" as const,
  },
  {
    id: "growth_streak",
    title: "Growth Streak",
    description: "6 months of consecutive portfolio growth",
    icon: "🌱",
    earned: false,
    progress: 75,
    rarity: "rare" as const,
  },
  {
    id: "emergency_fund",
    title: "Emergency Ready",
    description: "Built 6-month emergency fund",
    icon: "🛡️",
    earned: false,
    progress: 85,
    rarity: "common" as const,
  },
  {
    id: "millionaire",
    title: "Millionaire",
    description: "Reached $1,000,000 net worth",
    icon: "💎",
    earned: false,
    progress: 68,
    rarity: "legendary" as const,
  },
];
